### ISSUE TITLE
HttpContext.Current not preserved

### ISSUE THREAD

**Issue by rcollette** [cjbhaines/Log4Net.Async#2]
Should be resolvable by implementing StartForward as:

        private void StartForwarding()
        {
            if (!this.shutDownRequested)
            {
                HttpContext ctx = HttpContext.Current;
                Thread thread = new Thread(new ThreadStart(() =>
                {
                    HttpContext.Current = ctx;
                    this.ForwardingThreadExecute();
                }))
                {
                    Name = string.Format("{0} Forwarding Appender Thread", base.Name),
                    IsBackground = false
                };
                this.forwardingThread = thread;
                this.forwardingThread.Start();
            }
        }

**Comment by rcollette** [comment]
@cjbhaines  - Any chance you can push this to nuget?   A guy at my old company is using  a custom build but now this should work for him.

**Comment by cjbhaines** [comment]
I just pushed it. Sorry this took so long!

**Comment by rcollette** [comment]
Not a problem.  I just switched jobs myself and have zero time to spare.  I know how it goes.  I've working on another open source project for more than a year and it's still not ready to release.  OS is not an easy job.

**Comment by cjbhaines** [comment]
I just took on a new role as well so know how you feel! Good luck with the new job. I made you a contributor so you can now freely commit. I think that should also give you permission to deploy to NuGet from AppVeyor.
